# version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: authdb
    ports:
      - "5432:5432" 
  app:
    build: .
    container_name: auth_service
    depends_on:
      - db 
    ports:
    - "8000:8000"
    environment:
      DATABASE_URL: postgresql://authuser:strongpassword@db:5432/authdb